"""empty message

Revision ID: 68c518e195a3
Revises: None
Create Date: 2016-04-20 16:08:13.860487

"""

# revision identifiers, used by Alembic.
revision = '68c518e195a3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('coverage_ind', table_name='nucleotide_measurement_set')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('coverage_ind', 'nucleotide_measurement_set', ['coverage'], unique=False)
    ### end Alembic commands ###
