"""empty message

Revision ID: f2915281337b
Revises: None
Create Date: 2016-04-20 15:32:09.553301

"""

# revision identifiers, used by Alembic.
revision = 'f2915281337b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_reactivities')
    op.drop_table('structure_prediction_run')
    op.drop_table('nucleotide_measurement_set')
    op.drop_table('gene_location')
    op.drop_table('feature')
    op.drop_table('strain')
    op.drop_table('gene')
    op.drop_table('structure')
    op.drop_table('nucleotide_measurement_run')
    op.drop_table('transcript')
    op.drop_table('chromosome')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chromosome',
    sa.Column('strain_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('chromosome_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('sequence', mysql.LONGTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], name='chromosome_ibfk_1'),
    sa.PrimaryKeyConstraint('strain_id', 'chromosome_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('transcript',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('gene_id', mysql.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], name='transcript_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('nucleotide_measurement_run',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('strain_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], name='nucleotide_measurement_run_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('structure',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('structure_prediction_run_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('transcript_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('energy', mysql.FLOAT(), nullable=False),
    sa.Column('pc1', mysql.FLOAT(), nullable=False),
    sa.Column('pc2', mysql.FLOAT(), nullable=False),
    sa.Column('structure', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['structure_prediction_run_id'], ['structure_prediction_run.id'], name='structure_ibfk_1'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], name='structure_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('gene',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('strain',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('feature',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('transcript_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('type_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('strain_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('chromosome_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('direction', mysql.ENUM('forward', 'reverse'), nullable=False),
    sa.ForeignKeyConstraint(['strain_id', 'chromosome_id'], ['chromosome.strain_id', 'chromosome.chromosome_id'], name='feature_ibfk_1'),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], name='feature_ibfk_3'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], name='feature_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('gene_location',
    sa.Column('gene_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('strain_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('chromosome_id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('direction', mysql.ENUM('forward', 'reverse'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], name='gene_location_ibfk_2'),
    sa.ForeignKeyConstraint(['strain_id', 'chromosome_id'], ['chromosome.strain_id', 'chromosome.chromosome_id'], name='gene_location_ibfk_1'),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], name='gene_location_ibfk_3'),
    sa.PrimaryKeyConstraint('gene_id', 'strain_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('nucleotide_measurement_set',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nucleotide_measurement_run_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('transcript_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('coverage', mysql.FLOAT(), nullable=False),
    sa.Column('values', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['nucleotide_measurement_run_id'], ['nucleotide_measurement_run.id'], name='nucleotide_measurement_set_ibfk_1'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], name='nucleotide_measurement_set_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('structure_prediction_run',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('strain_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], name='structure_prediction_run_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('raw_reactivities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nucleotide_measurement_run_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('transcript_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('minus_values', mysql.TEXT(), nullable=False),
    sa.Column('plus_values', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['nucleotide_measurement_run_id'], ['nucleotide_measurement_run.id'], name='raw_reactivities_ibfk_1'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], name='raw_reactivities_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
