"""empty message

Revision ID: 09ddd9e7a518
Revises: c28390c05b73
Create Date: 2016-04-21 15:51:52.015018

"""

# This revision creates the BPPM table and extra field in structure. 
# It doesn't insert the BPPM data - see the next revision for that

revision = '09ddd9e7a518'
down_revision = 'c28390c05b73'

from alembic import op
from importers import BppmImporter
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # op.create_table('bppm',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('transcript_id', sa.String(length=256), nullable=False),
    #     sa.Column('data', mysql.LONGTEXT(), nullable=False),
    #     sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ),
    #     sa.PrimaryKeyConstraint('id')
    # )

    print("Adding bpps column (takes some time)")
    op.add_column('structure', sa.Column('bpps', sa.Text(), nullable=True))

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('bppm')

    print("Dropping bpps column (takes some time)")
    op.drop_column('structure', 'bpps')
    ### end Alembic commands ###
