"""empty message

Revision ID: 1740de11ccfe
Revises: None
Create Date: 2016-04-20 16:24:33.697805

"""

# revision identifiers, used by Alembic.
revision = '1740de11ccfe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
	print("First migrate, nothing to do here")

    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('coverage_ind', table_name='nucleotide_measurement_set')
    ### end Alembic commands ###




def downgrade():
	print("First migrate, nothing to do here")
	
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('coverage_ind', 'nucleotide_measurement_set', ['coverage'], unique=False)
    ### end Alembic commands ###

    
